### ISSUE TITLE
Should this gitlab module not reside on gitlab?

### ISSUE THREAD

**Issue by sbp-bvanb** [schubergphilis/terraform-gitlab-mcaf-project#6]
https://gitlab.com/schubergphilis

**Comment by marwinbaumannsbp** [comment]
It does not matter if this repo is GitHub or GitLab, currently all the Terraform MCAF modules are created in GitHub and the preferred way of consuming the modules is via the public registry:

https://registry.terraform.io/modules/schubergphilis/mcaf-project/gitlab/latest

**Comment by sbp-bvanb** [comment]
Ok then I will also start sharing gitlab templates I need for multiple teams that reside in private gitlab spaces through GitHub. @gitbluf FYI.
